# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetIpAddress', '0003_agentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinfo',
            name='Used',
            field=models.IntegerField(default=0),
        ),
    ]
