# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetIpAddress', '0004_agentinfo_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UrlName', models.CharField(max_length=16, verbose_name='Url名称')),
                ('UrlAddress', models.CharField(max_length=128, verbose_name='Url地址')),
                ('Used', models.IntegerField(default=0)),
            ],
        ),
    ]
