# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetIpAddress', '0005_urlinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinfo',
            name='AgentPort',
            field=models.IntegerField(default=0, max_length=16, verbose_name='端口'),
        ),
    ]
