# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetIpAddress', '0006_agentinfo_agentport'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlinfo',
            name='Checked',
            field=models.IntegerField(default=0),
        ),
    ]
