# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetIpAddress', '0007_urlinfo_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinfo',
            name='Api',
            field=models.CharField(default='/api', max_length=16, verbose_name='客户端API接口'),
            preserve_default=False,
        ),
    ]
