# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetIpAddress', '0008_agentinfo_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=16, verbose_name='用户名')),
                ('Password', models.CharField(max_length=16, verbose_name='密码')),
                ('Status', models.IntegerField(verbose_name='账号状态')),
            ],
        ),
    ]
